test:node22:
  stage: test
  image: node:22
  tags:
    - linux
  script:
    - npm install
    - npm run build
    - npm run test

test:node18:
  stage: test
  image: node:18
  tags:
    - linux
  script:
    - npm install
    - npm run build
    - npm run test
