test:node12:
  stage: test
  image: node:12
  tags:
    - linux
  script:
    - npm install
    - npm run build
    - npm run test

test:node16:
  stage: test
  image: node:16
  tags:
    - linux
  script:
    - npm install
    - npm run build
    - npm run test
